[package]
name = "triptych"
version = "0.1.0"
authors = ["Stephan van Ellewee <stephan.van.ellewee@gmail.com>"]

[dependencies.serde_json]
version = "1.0.15"

[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled","serde_json"]

